### ISSUE TITLE
Air conditioner - incorrect outside temperature

### ISSUE THREAD

**Issue by llhotka** [gvigroux/hon#20] opened 2022-09-21 19:27 UTC
I am using this integration with air conditioner Haier Expert 2.8 kW. Everything seems to work just fine, but I noticed that the outside temperature sensor gives bogus values that are also different from those reported by the hOn mobile app. For example, today the sensor reported 4°C throughout the whole day. This might possibly have been the lowest temperature in the morning, but during the day real outside temperature rose up to 16˚C, and hOn app tracked the changes during the day quite faithfully.

**Comment by efburgos** [comment] 2022-10-14 19:19
Hello,

I have a similar problem, outside sensor shows the set temperature for the A/C and not the outside temperature.
The outside temperature I see on the card to manage the AC.

my model is HAIER SPLIT GEOS GREEN 35 R32

Thanks for this integration!
![ac](https://user-images.githubusercontent.com/10208812/195924894-d439aa03-c0e8-4ce0-a718-96353fb4e7a4.jpg)

**Comment by gvigroux** [comment] 2023-03-12 09:54
That's strange. I've updated slightly the sensor (and added the indoor temperature sensor).
Can you check if the problem is still there?

**Comment by llhotka** [comment] 2023-03-13 08:36
I've pulled the changes and restarted HA. The indoor temperature sensor gives the same temperature as hOn app, but there is still a difference in outdoor temperature: the sensor reports 6˚C but h0n 9˚C. Currently I don't have an independent outdoor measurement but 9˚C is also shown in weather apps (that don't measure it directly at my place though). I wonder if the h0n app really uses the temperature measurement from the outdoor unit. Is there anything I could check?
Thanks, Lada

**Comment by gvigroux** [comment] 2023-03-23 21:46
I've updated the main branch to show all the available sensors (like temperatures). Please tell me what do you have now

**Comment by llhotka** [comment] 2023-03-24 07:05
The outdoor temperature sensor shows 20˚C whereas hOn app reports 13.5˚C. Here are all the attributes od the device entity:
![image](https://user-images.githubusercontent.com/381993/227449274-f45e6194-8250-48d2-9650-7ca5e1e22008.png)

**Comment by gvigroux** [comment] 2023-03-24 08:34
I need to analyse some logs to understand.
Please add this to the **configuration.yaml** and restart HA
```
logger:
  logs:
    custom_components.hon: info
```

After go to the log page '/config/logs' and click to access all logs.
Share any of the logs starting with:
`[custom_components.hon.hon] {"payload":`


Thanks!

**Comment by llhotka** [comment] 2023-03-24 09:06
Here it is:

```
2023-03-24 09:54:15.484 INFO (MainThread) [custom_components.hon.hon] {"payload":{"resultCode":"0","shadow":{"parameters":{"voiceStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"tempCoilerIndoor":{"parNewVal":"22.00","lastUpdate":"2023-03-24T01:38:45Z"},"tempSel":{"parNewVal":"22.00","lastUpdate":"2023-03-22T06:49:15Z"},"totalWorkTime":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"halfDegreeSettingStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"tempAirOutdoor":{"parNewVal":"32","lastUpdate":"2023-03-23T15:01:44Z"},"debugEnabled":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:43Z"},"co2ValueIndoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"tempInAirOutdoor":{"parNewVal":"-64","lastUpdate":"2022-06-21T16:17:26Z"},"selfCleaningStatus":{"parNewVal":"0","lastUpdate":"2022-12-27T20:57:46Z"},"pm2p5ValueIndoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"fanStatusOutdoor":{"parNewVal":"2","lastUpdate":"2022-06-21T16:17:26Z"},"tempUnit":{"parNewVal":"0","lastUpdate":"2022-07-11T18:01:10Z"},"stdTransRate":{"parNewVal":"3600","lastUpdate":"2022-06-21T16:16:43Z"},"intelligenceStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"airQuality":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"machMode":{"parNewVal":"4","lastUpdate":"2023-02-04T16:01:09Z"},"humidityIndoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"energySavingStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"vocValueIndoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"errors":{"parNewVal":"00","lastUpdate":"2022-06-21T16:16:43Z"},"defrostStatus":{"parNewVal":"0","lastUpdate":"2023-03-03T09:35:57Z"},"compressorFrequency":{"parNewVal":"0","lastUpdate":"2023-03-23T14:16:29Z"},"tempIndoor":{"parNewVal":"19.50","lastUpdate":"2023-03-24T02:08:56Z"},"healthMode":{"parNewVal":"0","lastUpdate":"2023-02-27T18:34:40Z"},"fourWayValveStatus":{"parNewVal":"2","lastUpdate":"2022-06-21T16:17:26Z"},"10degreeHeatingStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"freshAirStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"expansionValveOpenDegree":{"parNewVal":"350","lastUpdate":"2023-03-23T14:18:30Z"},"windDirectionVertical":{"parNewVal":"5","lastUpdate":"2022-11-08T05:36:05Z"},"muteStatus":{"parNewVal":"0","lastUpdate":"2022-06-25T20:19:39Z"},"onOffStatus":{"parNewVal":"0","lastUpdate":"2023-03-23T14:50:54Z"},"lockStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"highTransRate":{"parNewVal":"1","lastUpdate":"2022-06-21T16:16:43Z"},"ch2oCleaningStatus":{"parNewVal":"0","lastUpdate":"2023-02-27T18:34:40Z"},"errAckFlag":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"windDirectionHorizontal":{"parNewVal":"0","lastUpdate":"2022-11-08T05:36:05Z"},"power":{"parNewVal":"0","lastUpdate":"2022-06-21T16:17:26Z"},"ch2oValueIndoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"machineModeHK":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"acType":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"tempCoilerOutdoor":{"parNewVal":"-64","lastUpdate":"2022-06-21T16:17:26Z"},"pm2p5LevelIndoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"heatAccumulationStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"sensingResult":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"screenDisplayStatus":{"parNewVal":"1","lastUpdate":"2023-03-21T05:20:33Z"},"silentSleepStatus":{"parNewVal":"0","lastUpdate":"2023-03-21T05:20:33Z"},"humanSensingStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"energySavePeriod":{"parNewVal":"15","lastUpdate":"2022-06-21T16:16:45Z"},"filterChangeStatusLocal":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"tempDefrostOutdoor":{"parNewVal":"20","lastUpdate":"2023-03-23T14:50:54Z"},"operationSource":{"parNewVal":"3","lastUpdate":"2022-11-08T05:36:05Z"},"pm2p5ValueOutdoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"lightStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"statusSyncRate":{"parNewVal":"1440","lastUpdate":"2022-07-20T13:54:28Z"},"electricHeatingStatusIndoor":{"parNewVal":"0","lastUpdate":"2022-06-21T16:17:26Z"},"tempOutdoor":{"parNewVal":"20.00","lastUpdate":"2023-03-23T15:01:44Z"},"pm2p5CleaningStatus":{"parNewVal":"0","lastUpdate":"2023-02-27T18:34:40Z"},"voiceSignStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"selfCleaning56Status":{"parNewVal":"0","lastUpdate":"2022-09-10T12:17:46Z"},"compressorCurrent":{"parNewVal":"51.10","lastUpdate":"2022-06-21T16:17:26Z"},"humiditySel":{"parNewVal":"30","lastUpdate":"2022-06-21T16:16:45Z"},"pmvStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"operationName":{"parNewVal":"","lastUpdate":"2022-07-19T20:40:48Z"},"echoStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"windSpeed":{"parNewVal":"5","lastUpdate":"2022-06-21T16:18:51Z"},"errCode":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"specialMode":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"windSensingStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"transMode":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:43Z"},"electricHeatingStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"compressorStatus":{"parNewVal":"0","lastUpdate":"2023-03-23T14:16:29Z"},"humidificationStatus":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"totalElectricityUsed":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"},"fanStatusIndoor":{"parNewVal":"0","lastUpdate":"2023-03-23T14:18:30Z"},"rapidMode":{"parNewVal":"0","lastUpdate":"2022-06-21T16:16:45Z"}}},"activity":{},"commandHistory":{"command":{"macAddress":"24-d7-eb-05-27-d4","commandName":"stopProgram","applianceOptions":{},"programName":"PROGRAMS.AC.IOT_HEAT","ancillaryParameters":{"remoteActionable":{"fixedValue":"1","typology":"fixed","category":"general","mandatory":0},"remoteVisible":{"fixedValue":"1","typology":"fixed","category":"general","mandatory":0}},"applianceType":"AC","attributes":{"prStr":"Vytápění","channel":"mobileApp","origin":"standardProgram"},"device":{"appVersion":"1.53.7","deviceModel":"oriole","osVersion":"33","mobileId":"13f0215ebba6cb58","mobileOs":"android"},"parameters":{"onOffStatus":"0"},"transactionId":"24-d7-eb-05-27-d4_2023-03-23T14:50:54.225Z","timestamp":"2023-03-23T14:50:54.225Z"},"timestampAccepted":"2023-03-23T14:50:52.6Z","timestampExecuted":"2023-03-23T14:50:53.3Z"},"lastConnEvent":{"macAddress":"24-d7-eb-05-27-d4","category":"CONNECTED","instantTime":"2023-03-24T08:50:43Z","timestampEvent":1679647843946}},"authInfo":{}}
```

**Comment by gvigroux** [comment] 2023-03-24 09:27
So the only interesting values are these one:

"tempCoilerIndoor":"22.00",
"tempSel": "22.00"
"tempAirOutdoor":"32"
"tempIndoor": "19.50"
"tempDefrostOutdoor":"20"
"tempOutdoor":"20.00"

The hOn app still display a value lower than 20?

**Comment by gvigroux** [comment] 2023-03-24 09:34
The game is to find in the list the value shown by the app :)

**Comment by llhotka** [comment] 2023-03-24 10:41
The app now shows 16˚C, which is not among the values above. Weird.

**Comment by gvigroux** [comment] 2023-03-27 08:45
I'm closing this issue because it seems the hOn app is taking this value from another place.
Still a strange case :)

**Closed by gvigroux** 2023-03-27 08:45 UTC
