### ISSUE TITLE
The air conditioner displays degrees in Fahrenheit instead of Celsius

### ISSUE THREAD

**Issue by pedroRSL** [gvigroux/hon#101] opened 2023-06-24 17:45 UTC
When starting or changing settings from Home Assistant, the display of the air conditioner shows degrees Fahrenheit instead of Celsius.  By changing the temperature with the remote control, it displays again in Celsius degrees. 
In Home Assistant, the temperature is displayed in Celsius. Model AS35TAMHRA-C.

**Comment by gvigroux** [comment] 2023-06-26 08:21
I'm (in theory) forcing the integration into CELSIUS all the time. Maybe I need to add this parameter as well when I change the temperature for certain devices.
Can you please dump a program that changes temperature ? (check readme)

**Comment by gvigroux** [comment] 2023-07-11 12:00
thanks, I will look into it

**Comment by gvigroux** [comment] 2023-08-01 08:02
I found probably the root cause, I will need some logs to investigate.

1. please add these lines in you configuration.yaml and reboot

```
logger:
  logs:
    custom_components.hon: debug
```
2. after the reboot, look at the log and share 2 info:
- the complete "[custom_components.hon.hon] Context for mac[" log
- any part of the "commands" log with the "tempUnit" paremter inside. You should have something like " 'tempUnit': {'category': 'command', 'typology': 'fixed', 'mandatory': 1, 'fixedValue': '1'}"

**Comment by flep11** [comment] 2023-08-01 18:45
The problem is no longer present in versions 0.6.0 and 0.6.1.
The temperature is displayed in degrees Celsius.
But I'll post the logs just in case.
[custom_components.hon.hon.txt](https://github.com/gvigroux/hon/files/12232996/custom_components.hon.hon.txt)
[custom_components.hon.hon Commands.txt](https://github.com/gvigroux/hon/files/12232997/custom_components.hon.hon.Commands.txt)

**Comment by gvigroux** [comment] 2023-08-02 08:06
Thank you so much for the help and the confirmation :)
Logs looks good.
I will close this issue !

**Closed by gvigroux** 2023-08-02 08:06 UTC
